FROM apache/airflow:2.1.0

USER root
RUN apt-get update && apt-get install -y \
    python3-dev \
    && apt-get clean

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

USER airflow
